kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dojo-user
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - ''
    resources:
      - services/proxy